trigger:
  branches:
    include:
      - main
      - feature/*
      - features/*
      - hotfix/*
      - hotfixes/*
      - support/*
  paths:
    include:
      - src/Enterprise.Dapper

resources:
  repositories:
    - repository: templates
      type: github
      name: melodic-software/devops-pipeline-templates
      endpoint: melodic-software
      ref: refs/heads/main

parameters:
  - name: releaseNotes
    displayName: Release Notes
    type: string
    default: N/A

pool:
  name: Azure Pipelines

extends:
  template: 'src/entry-points/create-nuget-package.yml@templates'
  parameters:
    projectName: Enterprise.Dapper
    targetFramework: DotNet
    dotNetSDKVersion: 8.x
    useGlobalJson: true
    releaseNotes: ${{ parameters.releaseNotes }}
    testProjects: []